FROM ubi8/ubi:8.3
MAINTAINER Eric <eric@example.com>
ARG NEXUS_VERSION=2.14.3-02
ENV NEXUS_HOME /opt/nexus
RUN yum -y install --setopt=tsflags=nodocs java-1.8.0-openjdk-devel && \
    groupadd -g 1001 nexus && \
    useradd -u 1001 -g 1001 -d ${NEXUS_HOME} -s /bin/false -m nexus && \
    chmod -R 755 ${NEXUS_HOME}
ADD nexus-2.14.3-02-bundle.tar.gz ${NEXUS_HOME}
ADD nexus-start.sh ${NEXUS_HOME}
RUN ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2 && \
    chown -R nexus:nexus ${NEXUS_HOME}
WORKDIR ${NEXUS_HOME}
USER nexus
VOLUME [ "/opt/nexus/sonatype-work" ]
CMD [ "sh" , "nexus-start.sh" ]




